
import __ASTRO_IMAGE_IMPORT_Z1AyhWV from "./4IiQQOEdmqPcCsjTqlta-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-in-tech-2024%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1p4q1D from "./lookback-design-tools-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2mwJGO from "./lookback-design-tools-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z181dEH from "./lookback-design-tools-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z25txkS from "./lookback-design-tools-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md";
import __ASTRO_IMAGE_IMPORT_22fgMR from "./lookback-design-tools-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1Yqs2V from "./product-designer-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fproduct-designer%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1zlJut from "./product-designer-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fproduct-designer%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2sVTyP from "./solo-designer-jobs-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fsolo-designer%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zk8J77 from "./jivalite.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fjiva-lite%2Findex.md";
export default new Map([["./4IiQQOEdmqPcCsjTqlta-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-in-tech-2024%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1AyhWV], ["./lookback-design-tools-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1p4q1D], ["./lookback-design-tools-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2mwJGO], ["./lookback-design-tools-3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md", __ASTRO_IMAGE_IMPORT_Z181dEH], ["./lookback-design-tools-4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md", __ASTRO_IMAGE_IMPORT_Z25txkS], ["./lookback-design-tools-5.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fdesign-tools-decade%2Findex.md", __ASTRO_IMAGE_IMPORT_22fgMR], ["./product-designer-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fproduct-designer%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1Yqs2V], ["./product-designer-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fproduct-designer%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1zlJut], ["./solo-designer-jobs-1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fwriting%2Fsolo-designer%2Findex.md", __ASTRO_IMAGE_IMPORT_2sVTyP], ["./jivalite.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fjiva-lite%2Findex.md", __ASTRO_IMAGE_IMPORT_Zk8J77]]);
		